### ISSUE TITLE
building and tagging?

### ISSUE THREAD

**Issue by sf105** [jmock-developers/jmock-packaging#1]
Looks like the jmock-library is geared up to manually build and tag a release (using the scripts files). Interestingly, this is still geared up for Subversion on Codehaus and not Github. Are these to be moved over to Git?

**Comment by sf105** [comment]
yes

**Comment by tobyweston** [comment]
I think this can be closed, replaced by [Issue 10](https://github.com/jmock-developers/jmock-library/issues/10) and [Issue 11](https://github.com/jmock-developers/jmock-library/issues/11)?
