### ISSUE TITLE
deployment?

### ISSUE THREAD

**Issue by sf105** [jmock-developers/jmock-packaging#5]
How do you want to handle to current two-stage process (build in jmock-library, deploy to Maven repository with jmock-packaging)? Would you prefer to take care of the build and publish from jmock-library and leave the Maven packaging in this project? Or redo the lot and aim for a single process?

**Comment by sf105** [comment]
don't know. open to ideas

**Comment by tobyweston** [comment]
If it's left as is, are you (or others) happy with the "process" of releasing just the code? If that's well known, I guess that makes the "release" part, at which point you can ask others to just do the maven push part. It at least makes a separation of responsibilities there. The maven push step would then be really simple and anyone can lend a hand by literally just running 'mvn deploy'.

**Comment by sf105** [comment]
I don't mind who does it. It would be good to have the thing documented and automated somewhere, so that any relevant person could do it.

S.

**Comment by tobyweston** [comment]
Closed? See previous issues
