### ISSUE TITLE
separate project

### ISSUE THREAD

**Issue by sf105** [jmock-developers/jmock-packaging#6]
The jmock-packaging project is separate from the jmock-library, so we don't get much from the Maven deploy process other than literally packaging and pushing to somewhere that Maven central can pick up. Not sure why jmock-library itself doesn't use Maven to be a more straight forward release / deploy process__

**Comment by sf105** [comment]
open to proposals. Probably should be a branch rather than a separate project

**Comment by mprins** [comment]
I'd like to see jmock move to maven as a build tool, this would (in the end) save quite some work during release cycles.

This would ideally require some reordering into separate module subtrees, one for each module.

**Comment by sf105** [comment]
I'm not so keen on that. For those of us who don't use mvn all the time, we can checkout and get started immediately. I'd prefer not to introduce the dependency. We don't release that often...

S.

**Comment by tobyweston** [comment]
Can we close this one then? Proposal is to keep Maven for pushing (pre-built) artifacts to central only.

**Comment by sf105** [comment]
I think so
