### ISSUE TITLE
publishing alternatives

### ISSUE THREAD

**Issue by sf105** [jmock-developers/jmock-packaging#7]
Publishing to Codehaus is facilitating with the Wagon Maven plugin, its pretty old and last time I tried it was all kinds of crazy. It'll need some testing to see if it still works. Worst case, moving away from Codehaus to say OSS Sonatype is pretty straight forward. It's picked up by Maven central but does add some manual steps to the process (basically approval and promotion within their web interface). Might be worth considering at some point.

**Comment by sf105** [comment]
open to proposals

**Comment by tobyweston** [comment]
This can be closed now, replaced by [Issue 12 against the main jmock-library project](https://github.com/jmock-developers/jmock-library/issues/12)
